# Generated by Django 6.0.4 on 2026-04-28 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('justified', models.BooleanField(default=False)),
                ('justification_file', models.FileField(blank=True, null=True, upload_to='absence_justifications/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
